### ISSUE TITLE
enhancement request avro schema

### ISSUE THREAD

**Issue by jorge80** [medale/spark-mail#7]
hi, is it possible to extend mailrecord  avro idl schema  with this below ? that can extend pretty analytics on it and not limited to enron only
Content-Type:
MIME-Version: 
Received: 
Authentication-Results: 
DKIM-Signature: 
From:
To: 
Subject:
Thread-Topic:
Thread-Index:
Date: 
Message-ID:
References:
In-Reply-To:
Accept-Language:
Content-Language:
X-MS-Has-Attach: 
X-MS-TNEF-Correlator: 
x-originating-ip:
X-Proofpoint-SPF-Result:
X-Proofpoint-SPF-Record:
X-Proofpoint-Virus-Version:
X-Proofpoint-Spam-Details:
X-Spam:
X-MAIL-FROM:
X-SOURCE-IP:
X-AnalysisOut:
Received-SPF: 
X-Auto-Response-Suppress:
Return-Path:
X-MS-Exchange-Organization-SCL:
Content-Transfer-Encoding:

**Comment by medale** [comment]
When you look at the current schema, you will see a mailFields map. All header key/value pairs that are not explicitly stored in the a top-level MailRecord field (e.g. from, to, subject, body) get parsed into that map. So you can still do analytics on those fields. 

record MailRecord {
    string uuid;
    string from;
    union{null, array<string>} to = null;
    union{null, array<string>} cc = null;
    union{null, array<string>} bcc = null;
    long dateUtcEpoch;
    string subject;
    union{null, map<string>} mailFields = null;
    string body;
    union{null, array<Attachment>} attachments = null;
  }

I also use mailFields to store additional metadata about a parsed email. For example, the Enron file-based email dataset uses directory names for user and folder names. See https://github.com/medale/spark-mail/blob/master/analytics/src/main/scala/com/uebercomputing/analytics/basic/FoldersPerUserStatistics.scala for an analytic that determines how many folders a user has. 

com.uebercomputing.mailrecord.Implicits.mailRecordToMailRecordOps has an implicit conversion from MailRecord to MailRecordOps. This adds the ability to retrieve a key in mailFields as an Option. Some(value) if it exists, None if the key was not in the record. For example:

val userNameOpt = mailRecord.getMailFieldOpt(MessageProcessor.UserName)

mailFields is a compromise to make MailRecord applicable to many different email sources rather than building many sparse MailRecord objects where lots of fields are undefined.

**Comment by jorge80** [comment]
thank you medale for your explanation, yesterday spend a lot of time to realized it how to, and now its clear
